package com.web.careus.enumeration;

public enum EServiceOffice {
    KECAMATAN_MIJEN,
    KECAMATAN_GUNUNG_PATI,
    KECAMATAN_BANYUMANIK,
    KECAMATAN_GAJAH_MUNGKUR,
    KECAMATAN_SEMARANG_SELATAN,
    KECAMATAN_CANDISARI,
    KECAMATAN_TEMBALANG,
    KECAMATAN_PEDURUNGAN,
    KECAMATAN_GENUK,
    KECAMATAN_GAYAMSARI,
    KECAMATAN_SEMARANG_TIMUR,
    KECAMATAN_SEMARANG_UTARA,
    KECAMATAN_SEMARANG_TENGAH,
    KECAMATAN_SEMARANG_BARAT,
    KECAMATAN_TUGU,
    KECAMATAN_NGALIYAN
}
