package com.web.careus.enumeration;

public enum ZakatCategory {
    ZAKAT_EMAS_PERAK_DAN_LOGAM_MULIA,
    ZAKAT_FITRAH,
    ZAKAT_MAAL,
    ZAKAT_PENDAPATAN_DAN_JASA,
    ZAKAT_PERNIAGAAN,
    ZAKAT_PERTAMBANGAN,
    ZAKAT_PERTANIAN_PERKEBUNAN_DAN_KEHUTANAN,
    ZAKAT_PERUSAHAAN,
    ZAKAT_PETERNAKAN_DAN_PERIKANAN,
    ZAKAT_PROFESI,
    ZAKAT_RIKAZ,
    ZAKAT_UANG_DAN_SURAT_BERHARGA_LAINNYA
}
